import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: '-- Panel Główny',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Strona startowa',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: '-- Moduły',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'calendar',
    title: 'Plan lekcji',
    moduleName: 'calendar',
    iconType: 'material-icons-two-tone',
    icon: 'date_range',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: 'badge bg-blue sidebar-badge float-right',
    submenu: [],
  },
  {
    path: 'task',
    title: 'Oceny',
    moduleName: 'task',
    iconType: 'material-icons-two-tone',
    icon: 'grade',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'tables',
    title: 'Egzaminy',
    moduleName: 'tables',
    iconType: 'material-icons-two-tone',
    icon: 'fact_check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: '-- Szkoła',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'media',
    title: 'Komunikaty szkolne',
    moduleName: 'media',
    iconType: 'material-icons-two-tone',
    icon: 'message',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'contacts',
    title: 'Kadra dydaktyczna',
    moduleName: 'contacts',
    iconType: 'material-icons-two-tone',
    icon: 'group',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
